### ISSUE TITLE
bin/k8s-client missing

### ISSUE THREAD

**Issue by matti** [k8s-ruby/k8s-ruby#26]
@Wai-Jiang 

This is missing from your commit:
```
  k8s-ruby:
    build: .
    volumes:
    - .:/app
    entrypoint: bundle exec bin/k8s-client
  ```
